# Put the following lines in your ~/.config/alacritty/alacritty.toml

[colors.primary]
background = "#1e1e1e"
foreground = "#d4d4d4"

[colors.cursor]
cursor = "#d4d4d4"
text = "#1e1e1e"

[colors.selection]
text = "#d4d4d4"
background = "#303030"
